version: "3.8"
volumes:
  foodmarket-volume:
networks:
  foodmarket-network:

services:
  db:
    container_name: foodmarket-db
    image: "postgres:latest"
    environment:
      - POSTGRES_USERNAME=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=food_market_db
    ports:
      - "5432:5432"
    volumes:
      - foodmarket-volume-volume:/var/lib/postgresql/data
    networks:
      - foodmarket-network-network

  backend:
    container_name: foodmarket-api
    # Diambil dari Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - DIRECTORY_PATH=${DIRECTORY_PATH}
    networks:
      - foodmarket-network-network